# Note: this is a shared pipeline used by other repositories.
# Docs: https://docs.github.com/en/actions/using-workflows/reusing-workflows

name: "AlloAllo"

on: # yamllint disable-line rule:truthy
    workflow_call:
        inputs:
            issue-welcome:
                description: "Message to show to a contributor opening their first issue."
                required: false
                type: "string"
            pr-welcome:
                description: "Message to show to a contributor opening their first pull request."
                required: false
                type: "string"
            pr-merged:
                description: "Message to show to a contributor after first merged pull request."
                required: false
                type: "string"
            target-repo:
                description: "The repo to run this action on. This is to prevent actions from running on forks unless intended."
                required: true
                type: "string"

permissions:
    contents: "read"
    issues: "write"
    pull-requests: "write"

jobs:
    allo-allo:
        if: "github.repository == inputs.target-repo"
        name: "The welcome bot"
        runs-on: "ubuntu-latest"

        steps:
            - name: "Harden Runner"
              uses: "step-security/harden-runner@5c7944e73c4c2a096b17a9cb74d65b6c2bbafbde" # v2.9.1
              with:
                  egress-policy: "audit"

            - name: "AlloAllo"
              uses: "mechanical-ink/allo-allo@a73509525c37fba22bc0d0c4a076c6d6b963fb06" # v1.0.1
              with:
                  issueWelcome: "${{ inputs.issue-welcome }}"
                  prWelcome: "${{ inputs.pr-welcome }}"
                  prMerged: "${{ inputs.pr-merged }}"
                  token: "${{ secrets.GITHUB_TOKEN }}"
